#!/usr/bin/env node
/**
 * Generates src/data/iso3166.ts from data/iso3166.csv.
 *
 * The CSV is the ISO 3166-1 table with the UN M49 region columns, vendored so
 * the build needs no network. The output is a compact tuple array rather than
 * objects, because 249 rows of `{ numeric: ..., alpha2: ... }` is four times
 * the bytes for no gain once the lookup maps are built at runtime.
 *
 * Run `npm run iso3166` after editing the CSV or SHORT_NAMES. The output is
 * generated and should not be hand-edited.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * ISO's formal names are not what anyone puts on a map. These are the names
 * a reader expects; everything else keeps the ISO name.
 */
const SHORT_NAMES = {
  BO: "Bolivia",
  BN: "Brunei",
  CV: "Cape Verde",
  CD: "DR Congo",
  CG: "Congo",
  CI: "Ivory Coast",
  CZ: "Czechia",
  FK: "Falkland Islands",
  FM: "Micronesia",
  IR: "Iran",
  KP: "North Korea",
  KR: "South Korea",
  LA: "Laos",
  MD: "Moldova",
  NL: "Netherlands",
  PS: "Palestine",
  RU: "Russia",
  SH: "Saint Helena",
  SY: "Syria",
  TW: "Taiwan",
  TZ: "Tanzania",
  TR: "Turkey",
  GB: "United Kingdom",
  US: "United States",
  VE: "Venezuela",
  VN: "Vietnam",
  VA: "Vatican City",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  UM: "U.S. Minor Outlying Islands",
  MK: "North Macedonia",
  SZ: "Eswatini",
  TL: "Timor-Leste",
};

/** A minimal CSV reader: the file has quoted fields but no embedded newlines. */
function parseCsv(text) {
  return text
    .trim()
    .split("\n")
    .map((line) => {
      const fields = [];
      let field = "";
      let quoted = false;
      for (const char of line) {
        if (char === '"') quoted = !quoted;
        else if (char === "," && !quoted) {
          fields.push(field);
          field = "";
        } else field += char;
      }
      fields.push(field);
      return fields;
    });
}

const [header, ...rows] = parseCsv(readFileSync(join(root, "data/iso3166.csv"), "utf8"));
const column = (name) => {
  const index = header.indexOf(name);
  if (index === -1) throw new Error(`iso3166.csv has no "${name}" column`);
  return index;
};

const NAME = column("name");
const ALPHA2 = column("alpha-2");
const ALPHA3 = column("alpha-3");
const NUMERIC = column("country-code");
const REGION = column("region");
const SUBREGION = column("sub-region");
const INTERMEDIATE = column("intermediate-region");

const tuples = rows
  .map((row) => [
    row[NUMERIC],
    row[ALPHA2],
    row[ALPHA3],
    SHORT_NAMES[row[ALPHA2]] ?? row[NAME],
    row[REGION],
    row[SUBREGION],
    row[INTERMEDIATE],
  ])
  .sort((a, b) => a[0].localeCompare(b[0]));

const lines = tuples.map((t) => `  ${JSON.stringify(t)},`).join("\n");

const output = `/**
 * ISO 3166-1 countries with their UN M49 region and sub-region.
 *
 * GENERATED by scripts/build-iso3166.mjs from data/iso3166.csv. Do not edit
 * by hand: change the CSV or the short-name list in the script and rerun
 * \`npm run iso3166\`.
 *
 * Each row is [numeric, alpha2, alpha3, name, region, subRegion,
 * intermediateRegion]. The last is often empty.
 */

export type IsoRow = readonly [
  numeric: string,
  alpha2: string,
  alpha3: string,
  name: string,
  region: string,
  subRegion: string,
  intermediateRegion: string,
];

export const ISO3166: readonly IsoRow[] = [
${lines}
];
`;

writeFileSync(join(root, "src/data/iso3166.ts"), output);
console.log(`src/data/iso3166.ts written: ${tuples.length} countries`);
